# Generated by Django 5.0.2 on 2024-02-14 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Last_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Last_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment_Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_no', models.CharField(max_length=12)),
                ('shipper_name', models.CharField(max_length=100)),
                ('shipper_phone', models.CharField(max_length=50)),
                ('shipper_address', models.CharField(max_length=200)),
                ('shipper_email', models.EmailField(max_length=254)),
                ('receivers_name', models.CharField(max_length=100)),
                ('receivers_phone', models.CharField(max_length=50)),
                ('receivers_address', models.CharField(max_length=200)),
                ('receivers_email', models.EmailField(max_length=254)),
                ('weight', models.CharField(max_length=50)),
                ('package', models.CharField(max_length=150)),
                ('product', models.CharField(max_length=200)),
                ('departure_time', models.TimeField()),
                ('pickup_time', models.TimeField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('courier_name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=50)),
                ('total_frieght', models.FloatField()),
                ('carrier_reference_no', models.CharField(blank=True, max_length=50, null=True)),
                ('pickup_date', models.DateField()),
                ('expected_delivery_date', models.DateField()),
                ('feature_image', models.ImageField(blank=True, null=True, upload_to='shipment-images')),
                ('remark', models.TextField(blank=True, null=True)),
                ('publish', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=3)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='carrier', to='cargo.shipmentcarrier')),
                ('current_location_in_transit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_location', to='cargo.shipmentlocation')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='destination', to='cargo.shipmentlocation')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mode', to='cargo.shipmentmode')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='origin', to='cargo.shipmentlocation')),
                ('payment_mode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_mothod', to='cargo.paymentmethod')),
                ('shipment_agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shipment.agent')),
                ('shipment_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shipment.client')),
                ('shipment_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shipment_type', to='cargo.shipmenttype')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='status', to='cargo.shipmentstatus')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipment.shipment_category')),
                ('tags', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipment.shipment_tags')),
            ],
        ),
        migrations.CreateModel(
            name='Shipmemt_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lacation', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.shipment')),
            ],
        ),
    ]
