# Generated by Django 5.0.2 on 2024-02-14 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_rename_shipmenttype_shipmentmethod'),
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='shipment_type',
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cargo.shipmentmethod'),
            preserve_default=False,
        ),
    ]
