# Generated by Django 5.0.2 on 2024-02-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_remove_shipment_shipment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmemt_history',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Picked up', 'Picked up'), ('Picked up', 'Picked up'), ('On Hold', 'On Hold'), ('Out for delivery', 'Out for delivery'), ('In Transit', 'In Transit'), ('Enroute', 'Enroute'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Returned', 'Returned')], default='Pending', max_length=100, null=True),
        ),
    ]
