# Generated by Django 5.0.2 on 2024-02-16 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0004_remove_shipment_current_location_in_transit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmemt_history',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_history', to='shipment.shipment'),
        ),
    ]
