# Generated by Django 5.0.2 on 2024-02-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0005_alter_shipmemt_history_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='tracking_no',
            field=models.CharField(max_length=20),
        ),
    ]
