# Generated by Django 5.0.2 on 2024-02-17 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0006_alter_shipment_tracking_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipment_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipment.agent'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipment.client'),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('Piece_type', models.CharField(blank=True, choices=[('Pallet', 'Pallet'), ('Carton', 'Carton'), ('Loose', 'Loose'), ('Crate', 'Crate'), ('Others', 'Others')], default='Pending', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField()),
                ('height', models.FloatField(blank=True, null=True)),
                ('value', models.FloatField()),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_package', to='shipment.shipment')),
            ],
        ),
    ]
