# Generated by Django 5.0.2 on 2024-02-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_logo', models.ImageField(upload_to='logo')),
                ('shipment_prefix', models.CharField(blank=True, max_length=5, null=True)),
                ('shipment_surfix', models.CharField(blank=True, max_length=5, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('email_subject', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PieaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieace_type', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_carrier', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_location', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_mode', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_status', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_shipment', models.TextField(unique=True)),
            ],
        ),
    ]
