# Generated by Django 5.0.2 on 2024-02-14 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShipmentType',
            new_name='ShipmentMethod',
        ),
    ]
