# Generated by Django 5.0.2 on 2024-02-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_rename_shipmenttype_shipmentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pieacetype',
            name='pieace_type',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shipmentcarrier',
            name='shipment_carrier',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shipmentlocation',
            name='shipment_location',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shipmentmethod',
            name='type_of_shipment',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shipmentmode',
            name='shipment_mode',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shipmentstatus',
            name='shipment_status',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
