# Generated by Django 5.0.2 on 2024-02-17 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0003_alter_paymentmethod_payment_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='shipment_prefix',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='shipment_surfix',
        ),
    ]
